# Generated by Django 6.0.3 on 2026-07-31 15:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tipo', models.CharField(blank=True, default='', max_length=50)),
                ('origem_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('criterio_pronto', models.CharField(blank=True, max_length=200)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('andamento', 'Em andamento'), ('concluida', 'Concluída')], default='aberta', max_length=20)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='projetos.projeto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'ordering': ['status', 'prazo', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApontamentoHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='projetos.projeto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamentos', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamentos', to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'apontamento de hora',
                'verbose_name_plural': 'apontamentos de horas',
                'ordering': ['-inicio'],
            },
        ),
    ]
