# Generated by Django 6.0.3 on 2026-08-01 14:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apontamentohora',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='apontamentohora',
            name='inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='início'),
        ),
        migrations.AlterField(
            model_name='apontamentohora',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamentos', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='criterio_pronto',
            field=models.CharField(blank=True, max_length=200, verbose_name='critério de pronto'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to=settings.AUTH_USER_MODEL, verbose_name='responsável'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='título'),
        ),
    ]
