# Generated by Django 6.0.3 on 2026-08-01 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('tarefas', '0002_alter_apontamentohora_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='fornecedor',
            field=models.ForeignKey(blank=True, help_text='Quando quem faz é de fora do escritório.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='fornecedores.fornecedor'),
        ),
    ]
