# Generated by Django 6.0.3 on 2026-08-02 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fases', '0005_lembrete_do_projeto'),
        ('tarefas', '0003_tarefa_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='fases.fase'),
        ),
    ]
