# Generated by Django 6.0.3 on 2026-08-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_tarefa_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='apontamentohora',
            name='pausado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pausado em'),
        ),
        migrations.AddField(
            model_name='apontamentohora',
            name='segundos_pausa',
            field=models.PositiveIntegerField(default=0, verbose_name='segundos em pausa'),
        ),
    ]
