# Generated by Django 6.0.3 on 2026-08-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cor_primaria',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='cor primária'),
        ),
    ]
