# Generated by Django 6.0.3 on 2026-08-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_empresa_cor_primaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagem_fundo',
            field=models.ImageField(blank=True, help_text='Foto larga que abre o painel. Sem ela, entra a imagem padrão.', null=True, upload_to='empresas/fundos/', verbose_name='imagem de fundo'),
        ),
    ]
