# Generated by Django 6.0.7 on 2026-08-03 00:43

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_imagem_fundo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='imagem_fundo',
            field=models.ImageField(blank=True, help_text='Foto larga que abre o painel. Sem ela, entra a imagem padrão.', null=True, upload_to='empresas/fundos/', validators=[core.uploads.validar_imagem], verbose_name='imagem de fundo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/', validators=[core.uploads.validar_imagem]),
        ),
    ]
