# Generated by Django 6.0.3 on 2026-07-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='horas_estimadas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Horas previstas (vindas da proposta). Comparadas com as trabalhadas.', max_digits=10),
        ),
    ]
