# Generated by Django 6.0.3 on 2026-08-01 14:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_horas_estimadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendencia',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='pendencia',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsável'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='ultima_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='última atualização'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='valor_contratado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor contratado'),
        ),
    ]
