# Generated by Django 6.0.3 on 2026-08-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_pendencia_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='aprovada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='aprovada em'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='data_prevista',
            field=models.DateField(blank=True, null=True, verbose_name='data prevista'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='data de início'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_prevista',
            field=models.DateField(blank=True, null=True, verbose_name='data prevista'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='horas_estimadas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Horas previstas (vindas da proposta). Comparadas com as trabalhadas.', max_digits=10, verbose_name='horas estimadas'),
        ),
    ]
