# Generated by Django 6.0.3 on 2026-08-01 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fornecedores', '0001_initial'),
        ('projetos', '0004_alter_etapa_aprovada_em_alter_etapa_data_prevista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='fornecedor',
            field=models.ForeignKey(blank=True, help_text='Quem executa esta etapa, quando é terceirizada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_projeto', to='fornecedores.fornecedor'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tem_execucao',
            field=models.BooleanField(default=False, help_text='Marque se o escritório também acompanha a obra. Muitos trabalhos terminam no projeto entregue.', verbose_name='acompanha a execução'),
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('arquitetonico', 'Arquitetônico'), ('estrutural', 'Estrutural'), ('hidraulico', 'Hidrossanitário'), ('eletrico', 'Elétrico'), ('climatizacao', 'Climatização'), ('incendio', 'Prevenção de incêndio'), ('luminotecnico', 'Luminotécnico'), ('paisagismo', 'Paisagismo'), ('interiores', 'Interiores'), ('marcenaria', 'Detalhamento de marcenaria'), ('outro', 'Outro')], default='arquitetonico', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=150, verbose_name='descrição')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('interna', models.BooleanField(default=True, help_text='Desmarque quando um projetista de fora assina esta disciplina.', verbose_name='feita pelo escritório')),
                ('prazo', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='fornecedores.fornecedor', verbose_name='projetista externo')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('projeto', 'nome'), name='disciplina_unica_por_projeto')],
            },
        ),
    ]
