# Generated by Django 6.0.3 on 2026-08-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_etapa_fornecedor_projeto_tem_execucao_disciplina'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='disciplina',
            name='disciplina_unica_por_projeto',
        ),
        migrations.AddField(
            model_name='projeto',
            name='area_construida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='área construída prevista (m²)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='area_terreno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='área do terreno (m²)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='cep',
            field=models.CharField(blank=True, max_length=12, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='cidade',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='projeto',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tipo',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('empresarial', 'Empresarial'), ('institucional', 'Institucional')], default='residencial', max_length=20),
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='projeto',
        ),
        migrations.DeleteModel(
            name='Etapa',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
