# Generated by Django 6.0.3 on 2026-08-02 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_tipologias_novas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pendencia',
        ),
    ]
