# Generated by Django 6.0.7 on 2026-08-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_remove_pendencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='tipo',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('empresarial', 'Empresarial'), ('institucional', 'Institucional'), ('urbanismo', 'Urbanismo')], default='residencial', max_length=20),
        ),
    ]
