# Generated by Django 6.0.3 on 2026-08-01 14:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('termos', 'Termos de uso'), ('privacidade', 'Política de privacidade')], max_length=20, verbose_name='tipo')),
                ('versao', models.CharField(help_text='Ex.: 1.0. Uma versão nova exige aceite de todos.', max_length=20, verbose_name='versão')),
                ('titulo', models.CharField(max_length=160, verbose_name='título')),
                ('resumo_mudancas', models.CharField(blank=True, help_text='O que mudou desde a versão anterior. Aparece na tela de aceite.', max_length=300, verbose_name='resumo das mudanças')),
                ('conteudo', models.TextField(help_text="Markdown simples: '## ' abre um título e linhas em branco separam parágrafos.", verbose_name='conteúdo')),
                ('vigente_desde', models.DateTimeField(blank=True, help_text='Em branco, a versão fica como rascunho e não é exigida de ninguém.', null=True, verbose_name='vigente desde')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'documento legal',
                'verbose_name_plural': 'documentos legais',
                'ordering': ['tipo', '-vigente_desde', '-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'versao'), name='documento_unico_por_versao')],
            },
        ),
        migrations.CreateModel(
            name='AceiteLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceito_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='aceito em')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='navegador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceites_legais', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceites', to='legal.documentolegal')),
            ],
            options={
                'verbose_name': 'aceite',
                'verbose_name_plural': 'aceites',
                'ordering': ['-aceito_em'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'documento'), name='aceite_unico_por_documento')],
            },
        ),
    ]
