# Generated by Django 6.0.3 on 2026-08-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisso',
            name='inicio',
            field=models.DateTimeField(verbose_name='início'),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='título'),
        ),
    ]
