# Generated by Django 6.0.3 on 2026-08-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_compromisso_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisso',
            name='tipo',
            field=models.CharField(choices=[('briefing', 'Reunião de briefing'), ('levantamento', 'Levantamento em campo'), ('apresentacao', 'Apresentação ao cliente'), ('reuniao', 'Reunião'), ('assinatura', 'Assinatura de contrato'), ('entrega', 'Entrega de fase'), ('orgao', 'Protocolo ou órgão público'), ('visita', 'Visita a obra'), ('medicao', 'Medição de obra'), ('prazo', 'Prazo/entrega'), ('outro', 'Outro')], default='reuniao', max_length=20),
        ),
    ]
