# Generated by Django 6.0.3 on 2026-07-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0002_configuracaoprecificacao_hora_tecnica_manual_and_more'),
        ('propostas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='fatores',
            field=models.ManyToManyField(blank=True, related_name='propostas', to='precificacao.fatorprecificacao'),
        ),
    ]
