# Generated by Django 6.0.3 on 2026-08-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0002_proposta_fatores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproposta',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='hora_tecnica_aplicada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='hora técnica aplicada'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='tipo_projeto',
            field=models.CharField(default='residencial', max_length=20, verbose_name='tipo de projeto'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='título'),
        ),
    ]
