# Generated by Django 6.0.3 on 2026-08-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0003_alter_itemproposta_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproposta',
            name='horas_estimadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='horas estimadas'),
        ),
    ]
