# Generated by Django 6.0.7 on 2026-08-03 17:51

from django.db import migrations, models


INCLUSOES = {
    "Briefing": "Roteiro de perguntas, programa de necessidades e consolidação das premissas do cliente.",
    "Estudo preliminar": "Conceito, referências, implantação ou layout inicial e apresentação para aprovação.",
    "Anteprojeto": "Plantas, cortes, fachadas, volumetria e definição preliminar de materiais e sistemas.",
    "Projeto executivo": "Desenhos executivos cotados, detalhamentos construtivos e informações para execução.",
}


def preencher_inclusoes(apps, schema_editor):
    Item = apps.get_model("propostas", "ItemProposta")
    for item in Item.objects.all().iterator():
        detalhe = next(
            (texto for trecho, texto in INCLUSOES.items() if trecho.casefold() in item.descricao.casefold()),
            "Entregáveis e atividades conforme o escopo desta etapa.",
        )
        Item.objects.filter(pk=item.pk).update(inclusoes=detalhe)


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0004_alter_itemproposta_horas_estimadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemproposta',
            name='inclusoes',
            field=models.TextField(default='Entregáveis e atividades conforme o escopo desta etapa.', help_text='Descreva os entregáveis e limites deste item.', verbose_name='o que inclui'),
        ),
        migrations.RunPython(preencher_inclusoes, migrations.RunPython.noop),
    ]
