# Generated by Django 6.0.7 on 2026-08-03 21:54

from datetime import timedelta

import django.core.validators
from django.db import migrations, models


def converter_validade_para_dias_uteis(apps, schema_editor):
    Proposta = apps.get_model("propostas", "Proposta")
    alteradas = []
    for proposta in Proposta.objects.exclude(validade__isnull=True):
        inicio = proposta.criado_em.date()
        dia = inicio
        quantidade = 0
        while dia < proposta.validade:
            dia += timedelta(days=1)
            if dia.weekday() < 5:
                quantidade += 1
        proposta.validade_dias_uteis = max(1, quantidade)
        alteradas.append(proposta)
    if alteradas:
        Proposta.objects.bulk_update(alteradas, ["validade_dias_uteis"])


def restaurar_validade_em_data(apps, schema_editor):
    Proposta = apps.get_model("propostas", "Proposta")
    alteradas = []
    for proposta in Proposta.objects.all():
        dia = proposta.criado_em.date()
        restantes = proposta.validade_dias_uteis
        while restantes:
            dia += timedelta(days=1)
            if dia.weekday() < 5:
                restantes -= 1
        proposta.validade = dia
        alteradas.append(proposta)
    if alteradas:
        Proposta.objects.bulk_update(alteradas, ["validade"])


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0005_itemproposta_inclusoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='validade_dias_uteis',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='validade (dias úteis)'),
        ),
        migrations.RunPython(
            converter_validade_para_dias_uteis,
            restaurar_validade_em_data,
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='validade',
        ),
    ]
