# Generated by Django 6.0.3 on 2026-08-01 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tipo', models.CharField(blank=True, default='', max_length=50)),
                ('origem_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('marcenaria', 'Marcenaria'), ('serralheria', 'Serralheria'), ('marmoraria', 'Marmoraria'), ('vidracaria', 'Vidraçaria'), ('eletrica', 'Elétrica'), ('hidraulica', 'Hidráulica'), ('climatizacao', 'Climatização'), ('gesso', 'Gesso e forro'), ('pintura', 'Pintura'), ('piso', 'Piso e revestimento'), ('iluminacao', 'Iluminação'), ('mobiliario', 'Mobiliário e decoração'), ('paisagismo', 'Paisagismo'), ('obra_civil', 'Obra civil'), ('projeto', 'Projeto complementar'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('contato', models.CharField(blank=True, max_length=150, verbose_name='pessoa de contato')),
                ('telefone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site', models.URLField(blank=True)),
                ('documento', models.CharField(blank=True, help_text='Só para emissão de nota.', max_length=30, verbose_name='CNPJ/CPF')),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('prazo_medio_dias', models.PositiveIntegerField(blank=True, help_text='Da aprovação à entrega.', null=True, verbose_name='prazo médio (dias)')),
                ('avaliacao', models.PositiveSmallIntegerField(blank=True, choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], help_text='Como foi trabalhar com ele da última vez.', null=True, verbose_name='avaliação')),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['nome'],
            },
        ),
    ]
