# Generated by Django 6.0.7 on 2026-08-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='categoria',
            field=models.CharField(choices=[('marcenaria', 'Marcenaria'), ('serralheria', 'Serralheria'), ('marmoraria', 'Marmoraria'), ('vidracaria', 'Vidraçaria'), ('eletrica', 'Elétrica'), ('hidraulica', 'Hidráulica'), ('climatizacao', 'Climatização'), ('gesso', 'Gesso e forro'), ('pintura', 'Pintura'), ('piso', 'Piso e revestimento'), ('iluminacao', 'Iluminação'), ('mobiliario', 'Mobiliário e decoração'), ('paisagismo', 'Paisagismo'), ('obra_civil', 'Obra civil'), ('projeto', 'Projeto complementar'), ('comunicacao_visual', 'Comunicação visual'), ('servicos_engenharia', 'Serviços de engenharia'), ('freelancer', 'Freelancer'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
    ]
