# Generated by Django 6.0.3 on 2026-07-31 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projetos', '0002_projeto_horas_estimadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObrigacaoTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tipo', models.CharField(blank=True, default='', max_length=50)),
                ('origem_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('art', 'ART (CREA)'), ('rrt', 'RRT (CAU)'), ('cau', 'Registro/vínculo CAU')], default='art', max_length=10)),
                ('numero', models.CharField(blank=True, max_length=60)),
                ('responsavel_tecnico', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('registrada', 'Registrada'), ('baixada', 'Baixada')], default='pendente', max_length=20)),
                ('data_registro', models.DateField(blank=True, null=True)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='regulatorio/%Y/%m/')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
                ('projeto', models.ForeignKey(blank=True, help_text='Deixe vazio para obrigações do escritório (ex.: registro CAU).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obrigacoes', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'obrigação técnica',
                'verbose_name_plural': 'obrigações técnicas',
                'ordering': ['status', 'vencimento', '-criado_em'],
            },
        ),
    ]
