# Generated by Django 6.0.3 on 2026-08-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrigacaotecnica',
            name='numero',
            field=models.CharField(blank=True, max_length=60, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='obrigacaotecnica',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='obrigacaotecnica',
            name='responsavel_tecnico',
            field=models.CharField(blank=True, max_length=150, verbose_name='responsável técnico'),
        ),
    ]
