# Generated by Django 6.0.3 on 2026-08-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio', '0002_alter_obrigacaotecnica_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrigacaotecnica',
            name='data_registro',
            field=models.DateField(blank=True, null=True, verbose_name='data de registro'),
        ),
    ]
