# Generated by Django 6.0.7 on 2026-08-03 00:43

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio', '0003_alter_obrigacaotecnica_data_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrigacaotecnica',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='regulatorio/%Y/%m/', validators=[core.uploads.validar_documento]),
        ),
    ]
