# Generated by Django 6.0.3 on 2026-08-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome_exibicao',
            field=models.CharField(blank=True, max_length=150, verbose_name='nome de exibição'),
        ),
    ]
