# Generated by Django 6.0.3 on 2026-08-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabancaria',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='saldo inicial'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='descrição'),
        ),
    ]
