# Generated by Django 6.0.3 on 2026-07-31 15:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPrecificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_uteis_mes', models.PositiveIntegerField(default=160, help_text='Horas realmente trabalhadas no mês (base da hora técnica).')),
                ('margem_seguranca_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Margem de segurança sobre as horas estimadas.', max_digits=5)),
                ('reserva_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Reserva do escritório (impostos, reinvestimento, imprevistos).', max_digits=5)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'configuração de precificação',
                'verbose_name_plural': 'configurações de precificação',
            },
        ),
        migrations.CreateModel(
            name='CustoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tipo', models.CharField(blank=True, default='', max_length=50)),
                ('origem_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=150)),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'custo fixo',
                'verbose_name_plural': 'custos fixos',
                'ordering': ['-valor_mensal', 'descricao'],
            },
        ),
    ]
