# Generated by Django 6.0.3 on 2026-07-31 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('precificacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoprecificacao',
            name='hora_tecnica_manual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se preenchida, é a hora técnica-base cobrada (sobrepõe o cálculo por custos). O valor por custos continua sendo o piso usado no cálculo de margem.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='FatorPrecificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Ajuste sobre a hora técnica-base, em %. Aceita valores negativos.', max_digits=6)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'fator de precificação',
                'verbose_name_plural': 'fatores de precificação',
                'ordering': ['-percentual', 'nome'],
            },
        ),
    ]
