# Generated by Django 6.0.3 on 2026-08-01 14:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0002_configuracaoprecificacao_hora_tecnica_manual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoprecificacao',
            name='hora_tecnica_manual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se preenchida, é a hora técnica-base cobrada (sobrepõe o cálculo por custos). O valor por custos continua sendo o piso usado no cálculo de margem.', max_digits=10, null=True, verbose_name='hora técnica manual'),
        ),
        migrations.AlterField(
            model_name='configuracaoprecificacao',
            name='horas_uteis_mes',
            field=models.PositiveIntegerField(default=160, help_text='Horas realmente trabalhadas no mês (base da hora técnica).', verbose_name='horas úteis por mês'),
        ),
        migrations.AlterField(
            model_name='configuracaoprecificacao',
            name='margem_seguranca_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Margem de segurança sobre as horas estimadas.', max_digits=5, verbose_name='margem de segurança (%)'),
        ),
        migrations.AlterField(
            model_name='configuracaoprecificacao',
            name='reserva_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Reserva do escritório (impostos, reinvestimento, imprevistos).', max_digits=5, verbose_name='reserva (%)'),
        ),
        migrations.AlterField(
            model_name='custofixo',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='custofixo',
            name='valor_mensal',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor mensal'),
        ),
    ]
