# Generated by Django 6.0.7 on 2026-08-03 18:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0004_reativar_itens_criados_pela_tela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoprecificacao',
            name='reserva_percent',
        ),
        migrations.AddField(
            model_name='configuracaoprecificacao',
            name='imposto_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual estimado de impostos incidente sobre o serviço.', max_digits=5, verbose_name='imposto (%)'),
        ),
        migrations.AddField(
            model_name='configuracaoprecificacao',
            name='lucro_previsto_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Lucro desejado sobre o custo do serviço.', max_digits=5, verbose_name='lucro previsto (%)'),
        ),
    ]
