# Generated by Django 6.0.7 on 2026-08-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0005_remove_configuracaoprecificacao_reserva_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoprecificacao',
            name='lucro_previsto_percent',
        ),
    ]
