# Generated by Django 6.0.3 on 2026-07-31 20:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('financeiro', '0002_initial'),
        ('projetos', '0002_projeto_horas_estimadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('data_prevista_inicio', models.DateField(blank=True, null=True)),
                ('data_prevista_fim', models.DateField(blank=True, null=True)),
                ('percentual_previsto', models.DecimalField(decimal_places=1, default=0, help_text='Avanço planejado até hoje (0–100).', max_digits=5)),
                ('percentual_real', models.DecimalField(decimal_places=1, default=0, help_text='Avanço executado (0–100).', max_digits=5)),
                ('valor', models.DecimalField(decimal_places=2, default=0, help_text='Valor da etapa; base da medição e do peso no cronograma.', max_digits=14)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'etapa de obra',
                'verbose_name_plural': 'etapas de obra',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('percentual_medido', models.DecimalField(decimal_places=1, default=0, help_text='Avanço verificado nesta medição.', max_digits=5)),
                ('valor_liberado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('aprovada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='obras.etapaobra')),
                ('lancamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='financeiro.lancamento')),
            ],
            options={
                'verbose_name': 'medição',
                'verbose_name_plural': 'medições',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tipo', models.CharField(blank=True, default='', max_length=50)),
                ('origem_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('endereco', models.CharField(blank=True, max_length=250)),
                ('responsavel_tecnico', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('andamento', 'Em andamento'), ('paralisada', 'Paralisada'), ('concluida', 'Concluída')], default='planejada', max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_prevista_fim', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obra', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'obra',
                'verbose_name_plural': 'obras',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='etapaobra',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='obras.obra'),
        ),
        migrations.CreateModel(
            name='VisitaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tipo', models.CharField(blank=True, default='', max_length=50)),
                ('origem_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('verificado', models.TextField(help_text='O que foi verificado na visita.')),
                ('pendencias', models.TextField(blank=True, help_text='Pendências a resolver (deixe vazio se ok).')),
                ('proxima_acao', models.CharField(blank=True, max_length=250)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='obras.etapaobra')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='obras.obra')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'visita técnica',
                'verbose_name_plural': 'visitas técnicas',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
