# Generated by Django 6.0.3 on 2026-08-01 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapaobra',
            name='percentual_previsto',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Avanço planejado até hoje (0–100).', max_digits=5, verbose_name='percentual previsto'),
        ),
        migrations.AlterField(
            model_name='etapaobra',
            name='percentual_real',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Avanço executado (0–100).', max_digits=5, verbose_name='percentual real'),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='percentual_medido',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Avanço verificado nesta medição.', max_digits=5, verbose_name='percentual medido'),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='valor_liberado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor liberado'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='endereco',
            field=models.CharField(blank=True, max_length=250, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='responsavel_tecnico',
            field=models.CharField(blank=True, max_length=150, verbose_name='responsável técnico'),
        ),
        migrations.AlterField(
            model_name='visitatecnica',
            name='pendencias',
            field=models.TextField(blank=True, help_text='Pendências a resolver (deixe vazio se ok).', verbose_name='pendências'),
        ),
        migrations.AlterField(
            model_name='visitatecnica',
            name='proxima_acao',
            field=models.CharField(blank=True, max_length=250, verbose_name='próxima ação'),
        ),
        migrations.AlterField(
            model_name='visitatecnica',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsável'),
        ),
    ]
