# Generated by Django 6.0.3 on 2026-08-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_alter_etapaobra_percentual_previsto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapaobra',
            name='data_prevista_fim',
            field=models.DateField(blank=True, null=True, verbose_name='fim previsto'),
        ),
        migrations.AlterField(
            model_name='etapaobra',
            name='data_prevista_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='início previsto'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='data de início'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='data_prevista_fim',
            field=models.DateField(blank=True, null=True, verbose_name='fim previsto'),
        ),
    ]
