# Generated by Django 6.0.3 on 2026-08-01 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fornecedores', '0001_initial'),
        ('projetos', '0006_remove_disciplina_disciplina_unica_por_projeto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tipo', models.CharField(blank=True, default='', max_length=50)),
                ('origem_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('chave', models.CharField(choices=[('briefing', 'Briefing'), ('proposta', 'Proposta e contrato'), ('estudo_preliminar', 'Estudo preliminar'), ('anteprojeto', 'Anteprojeto'), ('executivo', 'Projeto executivo'), ('comp_estrutural', 'Projeto estrutural'), ('comp_eletrica', 'Projeto elétrico'), ('comp_hidraulica', 'Projeto hidrossanitário'), ('comp_paisagismo', 'Paisagismo')], max_length=30)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('nao_iniciada', 'Não iniciada'), ('em_elaboracao', 'Em elaboração'), ('aguardando_cliente', 'Enviada ao cliente'), ('ajustes', 'Ajustes pedidos'), ('aprovada', 'Aprovada')], default='nao_iniciada', max_length=20)),
                ('prazo', models.DateField(blank=True, help_text='Data combinada de entrega.', null=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True, verbose_name='iniciada em')),
                ('enviada_em', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('respondida_em', models.DateTimeField(blank=True, null=True, verbose_name='respondida em')),
                ('parecer', models.TextField(blank=True, help_text='O que o cliente respondeu ao aprovar ou pedir ajuste.')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fases', to='fornecedores.fornecedor', verbose_name='projetista responsável')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'fase',
                'verbose_name_plural': 'fases',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comentario', 'Comentário interno'), ('cliente', 'Conversa com o cliente'), ('sistema', 'Registro do sistema')], default='comentario', max_length=15)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='fases.fase')),
            ],
            options={
                'verbose_name': 'registro da fase',
                'verbose_name_plural': 'registros da fase',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='fase',
            constraint=models.UniqueConstraint(fields=('projeto', 'chave'), name='fase_unica_por_projeto'),
        ),
    ]
