# Generated by Django 6.0.3 on 2026-08-01 22:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fases', '0002_fases_dos_projetos_existentes'),
        ('fornecedores', '0001_initial'),
        ('projetos', '0007_tipologias_novas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fase',
            name='fase_unica_por_projeto',
        ),
        migrations.AddField(
            model_name='fase',
            name='titulo_livre',
            field=models.CharField(blank=True, help_text='Só para complementar fora da lista — acústico, automação, luminotécnico.', max_length=120, verbose_name='nome do complementar'),
        ),
        migrations.AlterField(
            model_name='fase',
            name='chave',
            field=models.CharField(choices=[('briefing', 'Briefing'), ('proposta', 'Proposta e contrato'), ('estudo_preliminar', 'Estudo preliminar'), ('anteprojeto', 'Anteprojeto'), ('executivo', 'Projeto executivo'), ('comp_estrutural', 'Projeto estrutural'), ('comp_eletrica', 'Projeto elétrico'), ('comp_hidraulica', 'Projeto hidrossanitário'), ('comp_outro', 'Complementar'), ('comp_paisagismo', 'Paisagismo')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='fase',
            constraint=models.UniqueConstraint(condition=models.Q(('chave', 'comp_outro'), _negated=True), fields=('projeto', 'chave'), name='fase_unica_por_projeto'),
        ),
    ]
