# Generated by Django 6.0.3 on 2026-08-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fases', '0003_remove_fase_fase_unica_por_projeto_fase_titulo_livre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofase',
            name='fixado',
            field=models.BooleanField(default=False),
        ),
    ]
