# Generated by Django 6.0.3 on 2026-08-02 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fases', '0005_lembrete_do_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lembrete',
            name='fixado',
        ),
        migrations.RemoveField(
            model_name='lembrete',
            name='tipo',
        ),
    ]
