# Generated by Django 6.0.7 on 2026-08-03 17:51

from django.db import migrations, models


def preencher_prazos_sugeridos(apps, schema_editor):
    Fase = apps.get_model("fases", "Fase")
    sugestoes = {
        "estudo_preliminar": 15,
        "anteprojeto": 20,
        "executivo": 30,
        "comp_estrutural": 15,
        "comp_eletrica": 15,
        "comp_hidraulica": 15,
        "comp_paisagismo": 15,
        "comp_outro": 15,
    }
    for chave, dias in sugestoes.items():
        Fase.objects.filter(chave=chave, dias_uteis_proposta__isnull=True).update(
            dias_uteis_proposta=dias
        )


class Migration(migrations.Migration):

    dependencies = [
        ('fases', '0008_fase_tarefas_semeadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='dias_uteis_proposta',
            field=models.PositiveIntegerField(blank=True, help_text='Contados da assinatura do contrato, respeitando a sequência das fases.', null=True, verbose_name='prazo na proposta (dias úteis)'),
        ),
        migrations.RunPython(preencher_prazos_sugeridos, migrations.RunPython.noop),
    ]
