# Generated by Django 6.0.3 on 2026-07-31 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tipo', models.CharField(blank=True, default='', max_length=50)),
                ('origem_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('perfil_usuarios', models.TextField(blank=True, help_text='Quem ocupa o espaço e a rotina do dia a dia.')),
                ('orcamento_previsto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('prazo_desejado', models.DateField(blank=True, null=True)),
                ('restricoes', models.TextField(blank=True, help_text='Recuos, gabarito, taxa de ocupação, infraestrutura.')),
                ('referencias', models.TextField(blank=True, help_text='Links/observações de referências.')),
                ('estilo', models.CharField(blank=True, help_text='Prioridades estéticas.', max_length=200)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='briefing', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'briefing',
                'verbose_name_plural': 'briefings',
            },
        ),
        migrations.CreateModel(
            name='AmbientePrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area_aprox', models.DecimalField(blank=True, decimal_places=2, help_text='Área aproximada (m²).', max_digits=8, null=True)),
                ('uso', models.CharField(blank=True, max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='briefing.briefing')),
            ],
            options={
                'verbose_name': 'ambiente do programa',
                'verbose_name_plural': 'programa de necessidades',
                'ordering': ['id'],
            },
        ),
    ]
