# Generated by Django 6.0.3 on 2026-08-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambienteprograma',
            name='area_aprox',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Área aproximada (m²).', max_digits=8, null=True, verbose_name='área aproximada'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='orcamento_previsto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='orçamento previsto'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='prazo_desejado',
            field=models.DateField(blank=True, null=True, verbose_name='prazo desejado'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='referencias',
            field=models.TextField(blank=True, help_text='Links/observações de referências.', verbose_name='referências'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='restricoes',
            field=models.TextField(blank=True, help_text='Recuos, gabarito, taxa de ocupação, infraestrutura.', verbose_name='restrições'),
        ),
    ]
