# Generated by Django 6.0.3 on 2026-08-01 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('briefing', '0002_alter_ambienteprograma_area_aprox_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.CharField(blank=True, help_text='Agrupa as perguntas na tela (ex.: Rotina, Orçamento, Estilo).', max_length=80)),
                ('texto', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('opcao', 'Escolha uma opção'), ('multipla', 'Escolha várias'), ('texto', 'Resposta escrita'), ('numero', 'Número')], default='opcao', max_length=10)),
                ('ajuda', models.CharField(blank=True, max_length=250)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'pergunta do template',
                'verbose_name_plural': 'perguntas do template',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpcaoPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='briefing.perguntatemplate')),
            ],
            options={
                'verbose_name': 'opção de resposta',
                'verbose_name_plural': 'opções de resposta',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tipo', models.CharField(blank=True, default='', max_length=50)),
                ('origem_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('tipo_projeto', models.CharField(blank=True, help_text='Deixe em branco para servir a qualquer tipo.', max_length=20, verbose_name='tipo de projeto')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'template de briefing',
                'verbose_name_plural': 'templates de briefing',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='perguntatemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='briefing.templatebriefing'),
        ),
        migrations.CreateModel(
            name='RespostaBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, verbose_name='complemento')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='briefing.briefing')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
                ('opcoes', models.ManyToManyField(blank=True, related_name='respostas', to='briefing.opcaopergunta')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='briefing.perguntatemplate')),
            ],
            options={
                'verbose_name': 'resposta do briefing',
                'verbose_name_plural': 'respostas do briefing',
                'ordering': ['pergunta__ordem', 'id'],
                'constraints': [models.UniqueConstraint(fields=('briefing', 'pergunta'), name='resposta_unica_por_pergunta')],
            },
        ),
    ]
