# Generated by Django 6.0.3 on 2026-08-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefing', '0003_perguntatemplate_opcaopergunta_templatebriefing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambienteprograma',
            name='quantidade',
            field=models.PositiveSmallIntegerField(default=1, help_text='Quantos ambientes desse tipo (3 dormitórios, 2 banheiros).'),
        ),
    ]
