# Generated by Django 6.0.3 on 2026-08-02 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briefing', '0004_ambienteprograma_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambienteprograma',
            name='quantidade',
        ),
    ]
