# Generated by Django 6.0.3 on 2026-07-31 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('mensagem', models.CharField(blank=True, max_length=300)),
                ('nivel', models.CharField(choices=[('info', 'Informação'), ('alerta', 'Alerta'), ('critico', 'Crítico')], default='alerta', max_length=10)),
                ('url', models.CharField(blank=True, help_text='Link relativo para a origem.', max_length=300)),
                ('chave', models.CharField(blank=True, max_length=120)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['lida', '-criado_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('lida', False)), fields=('empresa', 'chave'), name='notificacao_chave_unica_por_empresa')],
            },
        ),
    ]
