# Generated by Django 6.0.3 on 2026-08-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0003_avisosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisosistema',
            name='onde',
            field=models.CharField(blank=True, max_length=160, verbose_name='onde'),
        ),
        migrations.AddField(
            model_name='avisosistema',
            name='url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
