# Generated by Django 6.0.3 on 2026-08-01 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fornecedores', '0001_initial'),
        ('projetos', '0004_alter_etapa_aprovada_em_alter_etapa_data_prevista_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tipo', models.CharField(blank=True, default='', max_length=50)),
                ('origem_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(default='Orçamento de execução', max_length=200, verbose_name='título')),
                ('versao', models.CharField(default='1', help_text='Suba a versão a cada revisão enviada.', max_length=20, verbose_name='versão')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado ao cliente'), ('aprovado', 'Aprovado'), ('revisado', 'Substituído por revisão')], default='rascunho', max_length=20)),
                ('bdi_percent', models.DecimalField(decimal_places=2, default=0, help_text='Benefícios e despesas indiretas aplicados sobre o custo dos itens.', max_digits=5, verbose_name='BDI (%)')),
                ('validade', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'orçamento',
                'verbose_name_plural': 'orçamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(blank=True, help_text='Ambiente ou frente de obra (ex.: cozinha).', max_length=120)),
                ('categoria', models.CharField(choices=[('demolicao', 'Demolição e remoção'), ('alvenaria', 'Alvenaria e estrutura'), ('instalacoes', 'Instalações'), ('revestimento', 'Revestimentos'), ('marcenaria', 'Marcenaria'), ('serralheria', 'Serralheria e vidros'), ('pintura', 'Pintura'), ('iluminacao', 'Iluminação'), ('mobiliario', 'Mobiliário e decoração'), ('paisagismo', 'Paisagismo'), ('mao_de_obra', 'Mão de obra'), ('taxas', 'Taxas e aprovações'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('descricao', models.CharField(max_length=250, verbose_name='descrição')),
                ('unidade', models.CharField(choices=[('un', 'un'), ('m', 'm'), ('m2', 'm²'), ('m3', 'm³'), ('kg', 'kg'), ('vb', 'verba'), ('h', 'h'), ('mes', 'mês')], default='un', max_length=5)),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor unitário')),
                ('valor_realizado', models.DecimalField(blank=True, decimal_places=2, help_text='Preencha quando o item for efetivamente contratado ou pago.', max_digits=12, null=True, verbose_name='valor realizado')),
                ('observacoes', models.CharField(blank=True, max_length=250, verbose_name='observações')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_orcamento', to='fornecedores.fornecedor')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamentos.orcamento')),
            ],
            options={
                'verbose_name': 'item do orçamento',
                'verbose_name_plural': 'itens do orçamento',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
