# Generated by Django 6.0.3 on 2026-08-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alteracaoescopo',
            name='descricao',
            field=models.TextField(verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero',
            field=models.CharField(blank=True, max_length=40, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor total'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='descricao',
            field=models.CharField(blank=True, max_length=120, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='numero',
            field=models.PositiveIntegerField(default=1, verbose_name='número'),
        ),
    ]
