# Generated by Django 6.0.3 on 2026-08-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_alter_alteracaoescopo_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alteracaoescopo',
            name='valor_delta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Impacto no valor (+/-).', max_digits=14, verbose_name='variação de valor'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_assinatura',
            field=models.DateField(blank=True, null=True, verbose_name='data de assinatura'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='parcelas_lancadas',
            field=models.BooleanField(default=False, verbose_name='parcelas lançadas'),
        ),
    ]
