# Generated by Django 6.0.3 on 2026-08-01 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contratos', '0003_alter_alteracaoescopo_valor_delta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='corpo',
            field=models.TextField(blank=True, help_text='Cláusulas do contrato. Gere a partir de um modelo e revise aqui.', verbose_name='texto do contrato'),
        ),
        migrations.CreateModel(
            name='ModeloContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tipo', models.CharField(blank=True, default='', max_length=50)),
                ('origem_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(blank=True, max_length=250, verbose_name='descrição')),
                ('corpo', models.TextField(help_text='Use marcadores como {{cliente}} e {{valor}}; eles são trocados ao gerar.')),
                ('padrao', models.BooleanField(default=False, help_text='Sugerido primeiro ao criar um contrato.', verbose_name='modelo padrão')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'modelo de contrato',
                'verbose_name_plural': 'modelos de contrato',
                'ordering': ['-padrao', 'nome'],
            },
        ),
    ]
