# Generated by Django 6.0.3 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0004_contrato_corpo_modelocontrato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="status",
            field=models.CharField(
                choices=[
                    ("rascunho", "Rascunho"),
                    ("enviado", "Enviado ao cliente"),
                    ("ajustes", "Em alterações"),
                    ("aprovado", "Aprovado"),
                    ("ativo", "Ativo (assinado)"),
                    ("encerrado", "Encerrado"),
                    ("cancelado", "Cancelado"),
                ],
                default="rascunho",
                max_length=20,
            ),
        ),
    ]
