# Generated by Django 6.0.7 on 2026-08-03 00:43

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_alteracaoescopo_tipos_contratuais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(upload_to='documentos/%Y/%m/', validators=[core.uploads.validar_documento]),
        ),
    ]
