# Generated by Django 6.0.7 on 2026-08-03 17:51

from django.db import migrations, models


def identificar_tipos(apps, schema_editor):
    Modelo = apps.get_model("contratos", "ModeloContrato")
    tipos = {
        "Projeto arquitetônico — pessoa física": "residencial",
        "Interiores com acompanhamento de obra": "residencial",
        "Projeto comercial — pessoa jurídica": "comercial",
    }
    for nome, tipo in tipos.items():
        Modelo.objects.filter(nome=nome, tipo_projeto="").update(tipo_projeto=tipo)


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_alter_documento_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelocontrato',
            name='tipo_projeto',
            field=models.CharField(blank=True, help_text='Deixe em branco para servir a qualquer tipo de projeto.', max_length=20, verbose_name='tipo de projeto'),
        ),
        migrations.RunPython(identificar_tipos, migrations.RunPython.noop),
    ]
