# Generated by Django 6.0.7 on 2026-08-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_modelocontrato_tipo_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocontrato',
            name='tipo_projeto',
            field=models.CharField(blank=True, choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('empresarial', 'Empresarial'), ('institucional', 'Institucional'), ('urbanismo', 'Urbanismo')], help_text='Deixe em branco para servir a qualquer tipo de projeto.', max_length=20, verbose_name='tipo de projeto'),
        ),
    ]
