# Generated by Django 6.0.3 on 2026-08-01 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tipo', models.CharField(blank=True, default='', max_length=50)),
                ('origem_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('arquivo', models.FileField(upload_to='arquivos/%Y/%m/')),
                ('fluxo', models.CharField(choices=[('enviado_cliente', 'Enviado ao cliente'), ('recebido_cliente', 'Recebido do cliente'), ('enviado_fornecedor', 'Enviado ao fornecedor'), ('recebido_fornecedor', 'Recebido do fornecedor'), ('orgao', 'Órgão público / concessionária'), ('interno', 'Interno do escritório')], default='interno', max_length=25)),
                ('categoria', models.CharField(choices=[('projeto', 'Prancha / projeto'), ('memorial', 'Memorial e especificação'), ('proposta', 'Proposta'), ('contrato', 'Contrato e aditivo'), ('orcamento', 'Orçamento'), ('nota', 'Nota fiscal'), ('recibo', 'Recibo / comprovante'), ('licenca', 'Licença e aprovação'), ('levantamento', 'Levantamento e medição'), ('foto', 'Foto de obra'), ('referencia', 'Referência e imagem'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('pago', 'Pago'), ('recusado', 'Recusado')], default='pendente', max_length=20)),
                ('data', models.DateField(blank=True, null=True, verbose_name='data de referência')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Só para nota, recibo ou orçamento — deixa o financeiro rastreável.', max_digits=14, null=True)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.group', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'arquivo',
                'verbose_name_plural': 'arquivos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
