# Generated by Django 6.0.3 on 2026-08-01 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arquivos', '0001_initial'),
        ('financeiro', '0003_alter_contabancaria_saldo_inicial_and_more'),
        ('fornecedores', '0001_initial'),
        ('projetos', '0004_alter_etapa_aprovada_em_alter_etapa_data_prevista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos', to='fornecedores.fornecedor'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='lancamento',
            field=models.ForeignKey(blank=True, help_text='Lançamento gerado no financeiro, quando houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='financeiro.lancamento'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='projetos.projeto'),
        ),
    ]
