# Generated by Django 6.0.3 on 2026-08-01 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0002_initial'),
        ('fases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='fase',
            field=models.ForeignKey(blank=True, help_text='A fase a que este arquivo pertence. Sem ela, o arquivo é do projeto todo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='fases.fase'),
        ),
    ]
