# Generated by Django 6.0.7 on 2026-08-03 00:43

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0004_arquivo_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(upload_to='arquivos/%Y/%m/', validators=[core.uploads.validar_documento]),
        ),
    ]
